plugins {
	id 'fabric-loom' version '1.10.5'
//	id 'org.jreleaser' version '1.19.0'
	id 'java-library'
	id 'maven-publish'
	id("tech.medivh.plugin.publisher") version "1.2.3"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	mavenCentral()
	maven {
		url 'https://plugins.gradle.org/m2/'
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

	include(implementation("org.reflections:reflections:0.10.2"))
	include(implementation("io.github.classgraph:classgraph:4.8.179"))
}


javadoc {
	options.memberLevel = JavadocMemberLevel.PROTECTED
	options.author = true
	options.version = true
	options.header = project.name
	options.addStringOption('Xdoclint:none', '-quiet')

	options.addStringOption("charset", "UTF-8")
	// suppress warnings due to cross-module @see and @link references;
	// note that global 'api' task does display all warnings.
	logging.captureStandardError LogLevel.INFO
	// suppress "## warnings" message
	logging.captureStandardOutput LogLevel.INFO
	options.encoding = "UTF-8"
	options.charSet = "UTF-8"
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
	withJavadocJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(AbstractArchiveTask).configureEach {
	jarTask -> jarTask.doLast{
		def file = jarTask.archiveFile.get().asFile
		if (file.exists()) {
			ant.checksum(algorithm: 'md5', file: file)
			ant.checksum(algorithm: 'sha1', file: file)
		} else {
			logger.warn("Checksum skipped: ${file} does not exist")
		}
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	options.annotationProcessorGeneratedSourcesDirectory = file("$buildDir/generated/sources/annotations")
}



jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}


medivhPublisher {
	groupId = project.maven_group.toString()
	artifactId = project.archives_base_name
	version = project.mod_version.toString()


	pom {
		name = "PC_Dev_Lib"
		description = project.description
		url = "https://github.com/Piscescup/PiscesCup-Develop-Lib/"
		licenses {
			license {
				name = "CC0 1.0 Universal"
				url = "https://opensource.org/licenses/MIT"
			}
		}
		developers {
			developer {
				id = "piscescup"
				name = "PiscesCup"
				email= "piscescup@outlook.com"
			}
		}
		scm {
			connection= "scm:git:https://github.com/Piscescup/PiscesCup-Develop-Lib.git"
			developerConnection= "scm:git:https://github.com/Piscescup/PiscesCup-Develop-Lib.git"
			url= "https://github.com/Piscescup/PiscesCup-Develop-Lib"
		}
	}
}

test {
	useJUnitPlatform()
}
