# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.12

# Mod Properties
mod_version=1.1.2+1.21.4
maven_group=io.github.piscescup
archives_base_name=pc_develop_lib
mod_name="PiscesCup Develop Lib"
description="This is a library for simple developing."
org.gradle.project.name="PiscesCup Develop Lib"


# Dependencies
fabric_version=0.119.2+1.21.4
fabric_api_version=0.119.2

lamp_version=4.0.0-rc.12

version=${mod_version}-fabric_${fabric_api_version}-mc_${minecraft_version}

artifact_name=${mod_name}-${version}

systemProp.org.gradle.internal.publish.checksums.insecure=true
